org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true

# Environment Properties
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.248
neo_version_range=[21.1,)
loader_version_range=[4,)

# Biomancy Mod Properties
mod_id=biomancy
mod_name=Biomancy
mod_license=MIT & CC-BY-NC-4.0
mod_major_version=2
mod_semantic_version=9.8.1-alpha.0
mod_group_id=com.github.elenterius
mod_vendor=Elenterius
mod_authors=Elenterius, RhinoW
mod_credits=The Shroome, kd8lvt, Shorepion, lordketer, Tarnisheart, Kitteh6660, Jasdan, ZeoMaddox, ItsLumine, RuskieThe3rd, M4rc3ll0 and many more people from the Biomancy Discord.
mod_description=Biopunk and Flesh Magic inspired tech-magic mod that has a fleshy art theme.
mod_url=https://modrinth.com/mod/biomancy
mod_issue_url=https://github.com/Elenterius/Biomancy/issues
mod_update_url=https://api.modrinth.com/updates/uAAuyU4M/forge_updates.json

# Dependencies

## Geckolib Mod
geckolib_version=4.7.6
geckolib_version_range=[4.7,)

## Just Enough Items (JEI) Mod
jei_version=19.21.0.247
jei_version_range=[19.21.0,)

## Curios
curios_version=9.5.1+1.21.1
curios_version_range=[9.5.1+1.21.1,)

## KubeJS
kubejs_version=2101.7.2-build.286

## Pehkui
pehkui_version=3.8.3-1.21-neoforge

## Farmer's Delight
farmers_delight_version=1.21.1-1.2.4a
